package main

import (
	"bufio"
	"fmt"
	"io"
	"slices"
	"strings"
)

// A baseline is the committed record of two columns of the matrix: the
// requirement list and, per requirement, the vector handlers that cite it.
// The file is tab-separated, one requirement per line:
//
//	ID<TAB>runner/handler runner/handler ...
//
// The handler column is sorted and space-separated, and empty when no vector
// cites the requirement. Blank lines and lines starting with "#" are ignored.
// Comparing the matrix with the baseline makes a change of the specification
// or of the vectors visible in review instead of passing silently.

// BaselineEntry is one line of a baseline file.
type BaselineEntry struct {
	ID       string
	Handlers []string // sorted
}

const baselineHeader = `# Traceability baseline of wbft: requirement ID and the vector handlers
# citing it (sorted, space-separated; empty when no vector cites it).
# Generated by tools/tracegen -write-baseline; CI compares the matrix with
# this file (-baseline) and fails on any difference. See README.md,
# "Traceability matrix", for how to update it.
`

// Baseline returns the baseline entries of the matrix, in row order.
func (m Matrix) Baseline() []BaselineEntry {
	out := make([]BaselineEntry, len(m.Rows))
	for i, r := range m.Rows {
		out[i] = BaselineEntry{ID: r.ID, Handlers: slices.Clone(r.Handlers)}
	}
	return out
}

// WriteBaseline writes entries in the baseline file format.
func WriteBaseline(w io.Writer, entries []BaselineEntry) error {
	if _, err := io.WriteString(w, baselineHeader); err != nil {
		return err
	}
	for _, e := range entries {
		if _, err := fmt.Fprintf(w, "%s\t%s\n", e.ID, strings.Join(e.Handlers, " ")); err != nil {
			return err
		}
	}
	return nil
}

// ReadBaseline parses a baseline file. Handlers are sorted on reading so that
// a hand-edited line compares by content, not by order.
func ReadBaseline(r io.Reader, name string) ([]BaselineEntry, error) {
	var out []BaselineEntry
	seen := map[string]bool{}
	sc := bufio.NewScanner(r)
	sc.Buffer(make([]byte, 0, 64*1024), 16<<20)
	for n := 1; sc.Scan(); n++ {
		line := strings.TrimRight(sc.Text(), "\r")
		if strings.TrimSpace(line) == "" || strings.HasPrefix(line, "#") {
			continue
		}
		id, handlers, _ := strings.Cut(line, "\t")
		if !isID(id) {
			return nil, fmt.Errorf("%s:%d: %q is not a requirement ID", name, n, id)
		}
		if seen[id] {
			return nil, fmt.Errorf("%s:%d: requirement %s listed twice", name, n, id)
		}
		seen[id] = true
		hs := strings.Fields(handlers)
		for _, h := range hs {
			if runner, handler, ok := strings.Cut(h, "/"); !ok || runner == "" || handler == "" || strings.Contains(handler, "/") {
				return nil, fmt.Errorf("%s:%d: %q is not a runner/handler name", name, n, h)
			}
		}
		slices.Sort(hs)
		out = append(out, BaselineEntry{ID: id, Handlers: slices.Compact(hs)})
	}
	return out, sc.Err()
}

func isID(s string) bool {
	loc := idRE.FindStringIndex(s)
	return loc != nil && loc[0] == 0 && loc[1] == len(s)
}

// CompareBaseline returns one human-readable line per difference between the
// baseline (want) and the entries built from the current sources (got). A
// line starts with "+" for a requirement that is not in the baseline, "-" for
// a requirement of the baseline that is no longer in the matrix, and "~" for
// a requirement whose handler column changed, followed by the added (+) and
// removed (-) handlers. Lines follow the order of got, then the removed IDs in the order of want.
// No lines means the two agree.
func CompareBaseline(want, got []BaselineEntry) []string {
	wantByID := make(map[string][]string, len(want))
	for _, e := range want {
		wantByID[e.ID] = e.Handlers
	}
	gotIDs := make(map[string]bool, len(got))
	var diff []string
	for _, e := range got {
		gotIDs[e.ID] = true
		wh, ok := wantByID[e.ID]
		if !ok {
			diff = append(diff, fmt.Sprintf("+ %s  requirement not in the baseline (handlers: %s)", e.ID, orNone(e.Handlers)))
			continue
		}
		added, removed := setDiff(e.Handlers, wh), setDiff(wh, e.Handlers)
		if len(added) == 0 && len(removed) == 0 {
			continue
		}
		var parts []string
		for _, h := range added {
			parts = append(parts, "+"+h)
		}
		for _, h := range removed {
			parts = append(parts, "-"+h)
		}
		diff = append(diff, fmt.Sprintf("~ %s  handlers: %s", e.ID, strings.Join(parts, " ")))
	}
	for _, e := range want {
		if !gotIDs[e.ID] {
			diff = append(diff, fmt.Sprintf("- %s  requirement in the baseline but not in the matrix", e.ID))
		}
	}
	return diff
}

// setDiff returns the elements of a that are not in b, in the order of a.
func setDiff(a, b []string) []string {
	var out []string
	for _, x := range a {
		if !slices.Contains(b, x) {
			out = append(out, x)
		}
	}
	return out
}

func orNone(hs []string) string {
	if len(hs) == 0 {
		return "none"
	}
	return strings.Join(hs, " ")
}
